project:
  type: default
  output-dir: docs
  pre-render:
    - python3 week-02/sync-notes.py
  post-render:
    - python3 week-02/finalize-student.py
  render:
    - index.qmd
    - week-*/index.qmd
    - week-01/with-notes.qmd

    - week-02/presenter.qmd
    - week-02/with-notes.qmd
    - week-02/instructor-notes.qmd
